/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    BatchImportDialog: typeof import('./src/components/batch/BatchImportDialog.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    CodeBlock: typeof import('./src/components/chat/CodeBlock.vue')['default']
    ConversationSidebar: typeof import('./src/components/chat/ConversationSidebar.vue')['default']
    MessageActions: typeof import('./src/components/chat/MessageActions.vue')['default']
    MessageItem: typeof import('./src/components/chat/MessageItem.vue')['default']
    NotificationPanel: typeof import('./src/components/layout/NotificationPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    SourcesPanel: typeof import('./src/components/chat/SourcesPanel.vue')['default']
    ThinkingIndicator: typeof import('./src/components/chat/ThinkingIndicator.vue')['default']
    UserProfilePanel: typeof import('./src/components/profile/UserProfilePanel.vue')['default']
  }
}
